=== JaapD/selfdiagnose/src/site/resources/selfdiagnose-2.8.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:annotation>
		<xs:documentation>
		SelfDiagnose Configuration Schema.
		version 2.8, last edit September 9, 2016
		@author E.M.Micklei
		</xs:documentation>
	</xs:annotation>

	<xs:simpleType name="Severity">
		<xs:restriction base="xs:string">
			<xs:enumeration value="NONE" />
			<xs:enumeration value="WARNING" />
			<xs:enumeration value="CRITICAL" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="Task">
		<xs:attribute name="report" type="xs:boolean"/>
		<xs:attribute name="comment" type="xs:string"/>
		<xs:attribute name="timeout" type="xs:int"/>
		<xs:attribute name="severity" type="Severity"/>
	</xs:complexType>

	<!-- please keep tasks sorted by class name -->
	<xs:element name="checkatgcomponentproperty">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="Task">
					<xs:attribute name="component" type="xs:string" use="required"/>
					<xs:attribute name="pattern" type="xs:string"/>
					<xs:attribute name="var" type="xs:string"/>
					<!-- choice -->
					<xs:attribute name="property" type="xs:string" use="required"/>
					<!-- /choice -->
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="checkbeanproperty">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="Task">
					<xs:attribute name="bean" type="xs:string" use="required"/>
					<xs:attribute name="pattern" type="xs:string"/>
					<xs:attribute name="var" type="xs:string"/>
					<!-- choice -->
					<xs:attribute name="property" type="xs:string" use="required"/>
					<xs:attribute name="method" type="xs:string" />
					<!-- /choice -->
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="checkmbeanproperty">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="Task">
					<!-- choice -->
					<xs:attribute name="property" type="xs:string"/>
					<xs:attribute name="operation" type="xs:string"/>
					<!-- /choice -->
					<xs:attribute name="mbeanserverfactory" type="xs:string"/>
					<xs:attribute name="query" type="xs:string" use="required"/>
					<xs:attribute name="pattern" type="xs:string"/>
					<xs:attribute name="var" type="xs:string"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="checkclassloadable">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="Task">
					<xs:attribute name="name" type="xs:string" use="required"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="checkvaluematches">
		<xs:complexType>
			<xs:complexContent>
			<xs:extension base="Task">
				<xs:attribute name="var" type="xs:string"/>
				<xs:attribute name="value" type="xs:string"/>
				<xs:attribute name="pattern" type="xs:string"/>
			</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="checkendecaservice">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="Task">
					<xs:attribute name="host" type="xs:string" use="required"/>
					<xs:attribute name="port" type="xs:string" use="required"/>
					<xs:attribute name="query" type="xs:string" use="required"/>
					<xs:attribute name="var" type="xs:string"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="checkhttprequestheader">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="Task">
					<xs:attribute name="header" type="xs:string" use="required"/>
					<xs:attribute name="pattern" type="xs:string" />
					<xs:attribute name="var" type="xs:string"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="checksystemproperty">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="Task">
					<xs:attribute name="property" type="xs:string" use="required"/>
					<xs:attribute name="pattern" type="xs:string"/>
					<xs:attribute name="var" type="xs:string"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="checkdatabasetableexists">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="Task">
					<xs:attribute name="name" type="xs:string" use="required"/>
					<xs:attribute name="datasource" type="xs:string" use="required"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="checkdatasourceconnectable">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="Task">
					<xs:attribute name="name" type="xs:string" use="required"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="checkdirectoryaccessible">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="Task">
					<xs:attribute name="path" type="xs:string" use="required"/>
					<xs:attribute name="writeable" type="xs:boolean"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="checkfilecontainsstring">
		<xs:complexType>
			<xs:complexContent>
			<xs:extension base="Task">
				<xs:attribute name="string" type="xs:string" use="required"/>
				<!-- choice -->
				<xs:attribute name="name" type="xs:string"/>
				<xs:attribute name="url" type="xs:string"/>
				<!-- /choice -->
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="checkjndibinding">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="Task">
					<xs:attribute name="var" type="xs:string"/>
					<xs:attribute name="name" type="xs:string" use="required"/>
					<xs:attribute name="class" type="xs:string" />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="checkmethoddefined">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="Task">
					<xs:attribute name="name" type="xs:string" use="required"/>
					<xs:attribute name="class" type="xs:string" use="required"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="checkpropertyvaluesarejavatypes">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="Task">
					<xs:attribute name="name" type="xs:string" use="required"/>
					<xs:attribute name="filter" type="xs:string"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="checkresourceaccessible">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="Task">
					<xs:attribute name="name" type="xs:string" use="required"/>
					<xs:attribute name="var" type="xs:string"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="checkresourcebundlekey">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="Task">
					<xs:attribute name="name" type="xs:string" use="required"/>
					<xs:attribute name="key" type="xs:string" use="required"/>
					<xs:attribute name="var" type="xs:string"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="checkresourceproperty">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="Task">
					<xs:attribute name="url" type="xs:string"/>
					<xs:attribute name="name" type="xs:string"/>
					<xs:attribute name="property" type="xs:string" use="required" />
					<xs:attribute name="pattern" type="xs:string" />
					<xs:attribute name="var" type="xs:string"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="checkurlreachable">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="Task">
					<xs:attribute name="url" type="xs:string"/>
					<xs:attribute name="pattern" type="xs:string" />
					<xs:attribute name="var" type="xs:string"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="checkvalidurl">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="Task">
					<xs:attribute name="url" type="xs:string" use="required" />
					<xs:attribute name="var" type="xs:string"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="checkwebspherejmslistenerport">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="Task">
					<xs:attribute name="name" type="xs:string" use="required" />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="checkxmlcontent">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="Task">
					<xs:attribute name="name" type="xs:string" />
					<xs:attribute name="url" type="xs:string" />
					<xs:attribute name="xpath" type="xs:string" use="required" />
					<xs:attribute name="pattern" type="xs:string" />
					<xs:attribute name="var" type="xs:string"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="reportjvmruntimememory" type="Task" />

	<xs:element name="reportmavenpomproperties">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="Task">
					<xs:attribute name="name" type="xs:string" />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="reportproperties">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="Task">
					<xs:attribute name="value" type="xs:string" />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="reportmap">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="Task">
					<xs:attribute name="value" type="xs:string" />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="reportjamonmonitors" type="Task" />

    <xs:element name="checkspringdatasourceconnectable">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="Task">
					<xs:attribute name="name" type="xs:string" />
                    <xs:attribute name="profile" type="xs:string" />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
    </xs:element>
    <xs:element name="checkspringbeanproperty">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="Task">
					<xs:attribute name="id" type="xs:string" />
					<xs:attribute name="property" type="xs:string" />
					<xs:attribute name="operation" type="xs:string" />
					<xs:attribute name="pattern" type="xs:string" />
                    <xs:attribute name="profile" type="xs:string" />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
    </xs:element>

	<!-- framework elements -->
	<xs:element name="iterator">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tasks"/>
			</xs:sequence>
			<xs:attribute name="comment" type="xs:string" />

			<xs:attribute name="value" type="xs:string" />
			<xs:attribute name="var" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="selfdiagnose">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tasks"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="task">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="Task">
					<xs:attribute name="class" type="xs:string"/>
					<xs:attribute name="ref" type="xs:string"/>
					<xs:anyAttribute namespace="##any" processContents="lax" />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="tasks">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<!-- checks -->
				<xs:element ref="checkbeanproperty"/>
				<xs:element ref="checkclassloadable"/>
				<xs:element ref="checkvaluematches"/>
				<xs:element ref="checkdatabasetableexists"/>
				<xs:element ref="checkdatasourceconnectable"/>
				<xs:element ref="checkdirectoryaccessible"/>
				<xs:element ref="checkfilecontainsstring"/>
				<xs:element ref="checkhttprequestheader"/>
				<xs:element ref="checkjndibinding"/>
				<xs:element ref="checkpropertyvaluesarejavatypes"/>
				<xs:element ref="checkresourceaccessible"/>
				<xs:element ref="checkresourcebundlekey"/>
				<xs:element ref="checkresourceproperty"/>
				<xs:element ref="checksystemproperty"/>
				<xs:element ref="checkurlreachable"/>
				<xs:element ref="checkvalidurl"/>
				<xs:element ref="checkxmlcontent"/>
				<xs:element ref="reportjvmruntimememory" />
				<xs:element ref="reportmap" />
				<xs:element ref="reportmavenpomproperties" />
				<xs:element ref="reportproperties" />
				<xs:element ref="reportjamonmonitors" />
				<!-- vendor -->
				<xs:element ref="checkatgcomponentproperty"/>
				<xs:element ref="checkwebspherejmslistenerport"/>
				<xs:element ref="checkendecaservice"/>
				<xs:element ref="checkspringdatasourceconnectable" />
				<xs:element ref="checkspringbeanproperty" />
				<!-- specials -->
				<xs:element ref="task"/>
				<xs:element ref="iterator"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== JaapD/selfdiagnose/src/site/resources/selfdiagnose_ubs.xml
<?xml version="1.0"?>
<selfdiagnose
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://selfdiagnose.sourceforge.net/selfdiagnose-2.8.xsd">

	<tasks>
		<!-- CHECK CONFIG BESTANDEN -->
		<checkjndibinding name="url/config/ubs_userBeheerService/config" class="java.net.URL" var="config"/>
		<checkurlreachable url="${config}"/>
		<checkjndibinding name="url/config/ubs_userBeheerService/log4j" class="java.net.URL" var="log4j"/>
		<checkurlreachable url="${log4j}"/>
		<!-- CHECK DATASOURCE -->
		<checkjndibinding name="jdbc/oracle/ubs_userBeheerService-ubsDs" class="com.ibm.ws.rsadapter.jdbc.WSJdbcDataSource"/>
		<checkdatasourceconnectable name="jdbc/oracle/ubs_userBeheerService-ubsDs"/>
		<checkdatabasetableexists name="UBS_CONTEXT" datasource="jdbc/oracle/ubs_userBeheerService-ubsDs"/>
		<checkdatabasetableexists name="UBS_PROGRAMMA" datasource="jdbc/oracle/ubs_userBeheerService-ubsDs"/>
		<!-- CHECK MESSAGE QUEUES -->
		<checkjndibinding name="jms/mq/ubs_userBeheerServiceQCf" class="javax.jms.QueueConnectionFactory"/>
		<checkjndibinding name="jms/mq/ubs_userBeheerService-BRK2UBSQd" class="javax.jms.Queue" var="brk2ubs"/>
		<checkjndibinding name="jms/mq/ubs_userBeheerService-UBS2BRKQd" class="javax.jms.Queue" var="ubs2brk"/>
		<checkbeanproperty bean="${brk2ubs}" property="queueName" pattern=".*UBS\.BRK2UBS\.DAT\.AQ.*"/>
		<checkbeanproperty bean="${brk2ubs}" property="targetClient" pattern="0" />
		<checkbeanproperty bean="${ubs2brk}" property="queueName" pattern=".*UBS\.UBS2BRK\.DAT\.AQ.*"/>
		<checkbeanproperty bean="${ubs2brk}" property="targetClient" pattern="0"/>
		<!-- CHECK LISTENERPORT -->
		<checkwebspherejmslistenerport name="ubs_userBeheerServiceLp"/>
		<!-- CHECK MAIL SERVICE -->
		<checkjndibinding name="mail/MailService"/>

	</tasks>
</selfdiagnose>
